### ISSUE TITLE
AudioObject property needs switch on develop due to API changes

### ISSUE THREAD

**Issue by ryanfrancesconi** [rnine/AMCoreAudio#46]
Main is only available on macOS 12+:

![image](https://user-images.githubusercontent.com/2917795/129384426-1f58a69e-9822-458a-980d-fd0ec4baa573.png)

I see [this](https://github.com/WebKit/WebKit/blob/main/Source/WebCore/platform/mediastream/mac/CoreAudioCaptureDeviceManager.cpp), which is super gross:

```swift
static bool deviceHasOutputStreams(AudioObjectID deviceID)
{
    AudioObjectPropertyAddress address = {
        kAudioDevicePropertyStreamConfiguration,
        kAudioDevicePropertyScopeOutput,
#if HAVE(AUDIO_OBJECT_PROPERTY_ELEMENT_MAIN)
        kAudioObjectPropertyElementMain
#else
        ALLOW_DEPRECATED_DECLARATIONS_BEGIN
        kAudioObjectPropertyElementMaster
        ALLOW_DEPRECATED_DECLARATIONS_END
#endif
    };
    return deviceHasStreams(deviceID, address);
}
```

Big Sur:

![image](https://user-images.githubusercontent.com/2917795/129382394-c9e13719-a49b-44d4-8347-968499737331.png)

![image](https://user-images.githubusercontent.com/2917795/129381900-715a33c2-0b2b-47c0-a2f3-3a96d33b5d9d.png)

**Comment by rnine** [comment]
@ryanfrancesconi Can you check https://github.com/rnine/SimplyCoreAudio/commit/719f01e5fb675bfda866f961672bf2aacd21f923 on your end?

**Comment by ryanfrancesconi** [comment]
Sorry for the delay. Didn't see your update. I think this change is working - looks clever, but I can't test overall as the framework still doesn't compile: (macOS 11.4)

![image](https://user-images.githubusercontent.com/2917795/130470813-d3cf72e9-b9fd-477e-85b2-9401d07c3faa.png)

**Comment by ryanfrancesconi** [comment]
I think the same concept needs to be applied to all macOS 12 deprecations. At least for me as a macOS (not iOS) developer it's going to be along time before I would ever enforce compatibility with 12. I'd guess 5 years at least.

![image](https://user-images.githubusercontent.com/2917795/130472039-6b69df54-1c2d-41f5-80ab-3415c9aa79f0.png)

**Comment by ryanfrancesconi** [comment]
Good warning to not update to XCode 13 I guess....

**Comment by rnine** [comment]
@ryanfrancesconi Yeah. Good point!

Actually, would you be interested in becoming a project collaborator? I am afraid I don't have much time to commit to this project right now, so your help would be truly appreciated!

**Comment by ryanfrancesconi** [comment]
sure, I'd be happy to help. I didn't want to step on your toes with PRs but this project is quite important to what I'm doing!

**Comment by rnine** [comment]
Excellent! Invite sent!

**Comment by ryanfrancesconi** [comment]
So, i didn't have luck solving this with only swift, but using a C header file I think I have a working solution. I've added a mini C framework that is basically just this:

```c
#pragma once

#ifndef SimplyCoreAudio_h
#define SimplyCoreAudio_h

#include <Availability.h>
#import <AudioToolbox/AudioToolbox.h>

#ifdef __MAC_OS_X_VERSION_MAX_ALLOWED
    #if __MAC_OS_X_VERSION_MAX_ALLOWED < 120000

        CF_ENUM(AudioObjectPropertySelector)
        {
            kAudioHardwareServiceDeviceProperty_VirtualMainVolume = kAudioHardwareServiceDeviceProperty_VirtualMasterVolume,
            kAudioHardwareServiceDeviceProperty_VirtualMainBalance = kAudioHardwareServiceDeviceProperty_VirtualMasterBalance
        };

        AudioObjectPropertyScope kAudioObjectPropertyElementMain = kAudioObjectPropertyElementMaster;

        #define kAudioAggregateDeviceMainSubDeviceKey "master"

    #endif
#endif

#endif
```
I tested on beta xcode and 12.5.1 and it seems like this approach works. Hacky stuff like this doesn't seem like you should have to do this, but I'm unsure of another solution.

The nice part is that when adoption to the newer xcode is complete can just delete the C defines and the actual framework doesn't change code.

https://github.com/ryanfrancesconi/SimplyCoreAudio/blob/develop-C/Sources/SimplyCoreAudioC/SimplyCoreAudio.h
https://github.com/ryanfrancesconi/SimplyCoreAudio/tree/develop-C

Let me know if that seems like a good solution from your perspective, or is too gross.

**Comment by ryanfrancesconi** [comment]
with that approach, it just adds the newer renamed APIs as duplicates in the pre os12:

```swift
    func testAPIDeprecations() {
        let vmvc = kAudioHardwareServiceDeviceProperty_VirtualMainVolume
        let vmbc = kAudioHardwareServiceDeviceProperty_VirtualMainBalance
        let elementMain = kAudioObjectPropertyElementMain
        let subDeviceKey = kAudioAggregateDeviceMainSubDeviceKey

        Swift.print(vmvc, vmbc, elementMain, subDeviceKey)

        XCTAssertEqual(vmvc, 1986885219)
        XCTAssertEqual(vmbc, 1986880099)
        XCTAssertEqual(elementMain, 0)
        XCTAssertEqual(subDeviceKey, "master")
    }
```
I'm sure there is some kinda no-no to doing this, but it does work.

**Comment by rnine** [comment]
> So, i didn't have luck solving this with only swift, but using a C header file I think I have a working solution. I've added a mini C framework that is basically just this:
> 
> ```c
> #pragma once
> 
> #ifndef SimplyCoreAudio_h
> #define SimplyCoreAudio_h
> 
> #include <Availability.h>
> #import <AudioToolbox/AudioToolbox.h>
> 
> #ifdef __MAC_OS_X_VERSION_MAX_ALLOWED
>     #if __MAC_OS_X_VERSION_MAX_ALLOWED < 120000
> 
>         CF_ENUM(AudioObjectPropertySelector)
>         {
>             kAudioHardwareServiceDeviceProperty_VirtualMainVolume = kAudioHardwareServiceDeviceProperty_VirtualMasterVolume,
>             kAudioHardwareServiceDeviceProperty_VirtualMainBalance = kAudioHardwareServiceDeviceProperty_VirtualMasterBalance
>         };
> 
>         AudioObjectPropertyScope kAudioObjectPropertyElementMain = kAudioObjectPropertyElementMaster;
> 
>         #define kAudioAggregateDeviceMainSubDeviceKey "master"
> 
>     #endif
> #endif
> 
> #endif
> ```
> 
> I tested on beta xcode and 12.5.1 and it seems like this approach works. Hacky stuff like this doesn't seem like you should have to do this, but I'm unsure of another solution.
> 
> The nice part is that can just delete the C stuff and the actual framework doesn't change anything.
> 
> https://github.com/ryanfrancesconi/SimplyCoreAudio/blob/develop-C/Sources/SimplyCoreAudioC/SimplyCoreAudio.h
> https://github.com/ryanfrancesconi/SimplyCoreAudio/tree/develop-C
> 
> Let me know if that seems like a good solution from your perspective, or is too gross.

That seems fine to me. However, running `swift build` using command line tools for Xcode 13.0 (beta 5):

```
% swift --version
swift-driver version: 1.26.9 Apple Swift version 5.5 (swiftlang-1300.0.29.102 clang-1300.0.28.1)
Target: x86_64-apple-macosx11.0
```

I am still getting:

```
% swift build    
/Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:20:38: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainVolume': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
        guard validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterVolume,
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                     kAudioHardwareServiceDeviceProperty_VirtualMainVolume
AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterVolume:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been explicitly marked unavailable here
public var kAudioHardwareServiceDeviceProperty_VirtualMasterVolume: AudioObjectPropertySelector { get }
           ^
/Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:33:52: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainVolume': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
        guard let address = validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterVolume,
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                   kAudioHardwareServiceDeviceProperty_VirtualMainVolume
AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterVolume:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been explicitly marked unavailable here
public var kAudioHardwareServiceDeviceProperty_VirtualMasterVolume: AudioObjectPropertySelector { get }
           ^
/Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:45:52: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainVolume': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
        guard let address = validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterVolume,
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                   kAudioHardwareServiceDeviceProperty_VirtualMainVolume
AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterVolume:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been explicitly marked unavailable here
public var kAudioHardwareServiceDeviceProperty_VirtualMasterVolume: AudioObjectPropertySelector { get }
           ^
/Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:80:52: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterBalance' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainBalance': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
        guard let address = validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterBalance,
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                   kAudioHardwareServiceDeviceProperty_VirtualMainBalance
AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterBalance:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterBalance' has been explicitly marked unavailable here
public var kAudioHardwareServiceDeviceProperty_VirtualMasterBalance: AudioObjectPropertySelector { get }
           ^
/Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:96:52: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterBalance' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainBalance': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
        guard let address = validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterBalance,
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                   kAudioHardwareServiceDeviceProperty_VirtualMainBalance
AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterBalance:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterBalance' has been explicitly marked unavailable here
public var kAudioHardwareServiceDeviceProperty_VirtualMasterBalance: AudioObjectPropertySelector { get }
           ^
/Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:20:38: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainVolume': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
        guard validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterVolume,
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                     kAudioHardwareServiceDeviceProperty_VirtualMainVolume
AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterVolume:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been explicitly marked unavailable here
public var kAudioHardwareServiceDeviceProperty_VirtualMasterVolume: AudioObjectPropertySelector { get }
           ^
/Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:33:52: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainVolume': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
        guard let address = validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterVolume,
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                   kAudioHardwareServiceDeviceProperty_VirtualMainVolume
AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterVolume:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been explicitly marked unavailable here
public var kAudioHardwareServiceDeviceProperty_VirtualMasterVolume: AudioObjectPropertySelector { get }
           ^
/Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:45:52: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainVolume': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
        guard let address = validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterVolume,
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                   kAudioHardwareServiceDeviceProperty_VirtualMainVolume
AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterVolume:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been explicitly marked unavailable here
public var kAudioHardwareServiceDeviceProperty_VirtualMasterVolume: AudioObjectPropertySelector { get }
           ^
/Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:80:52: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterBalance' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainBalance': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
        guard let address = validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterBalance,
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                   kAudioHardwareServiceDeviceProperty_VirtualMainBalance
AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterBalance:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterBalance' has been explicitly marked unavailable here
public var kAudioHardwareServiceDeviceProperty_VirtualMasterBalance: AudioObjectPropertySelector { get }
           ^
/Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:96:52: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterBalance' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainBalance': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
        guard let address = validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterBalance,
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                   kAudioHardwareServiceDeviceProperty_VirtualMainBalance
AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterBalance:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterBalance' has been explicitly marked unavailable here
public var kAudioHardwareServiceDeviceProperty_VirtualMasterBalance: AudioObjectPropertySelector { get }
           ^
```

Works fine using command line tools for Xcode 12.5.1, though.

Running macOS 11.5.2 here.

**Comment by rnine** [comment]
> > So, i didn't have luck solving this with only swift, but using a C header file I think I have a working solution. I've added a mini C framework that is basically just this:
> > ```c
> > #pragma once
> > 
> > #ifndef SimplyCoreAudio_h
> > #define SimplyCoreAudio_h
> > 
> > #include <Availability.h>
> > #import <AudioToolbox/AudioToolbox.h>
> > 
> > #ifdef __MAC_OS_X_VERSION_MAX_ALLOWED
> >     #if __MAC_OS_X_VERSION_MAX_ALLOWED < 120000
> > 
> >         CF_ENUM(AudioObjectPropertySelector)
> >         {
> >             kAudioHardwareServiceDeviceProperty_VirtualMainVolume = kAudioHardwareServiceDeviceProperty_VirtualMasterVolume,
> >             kAudioHardwareServiceDeviceProperty_VirtualMainBalance = kAudioHardwareServiceDeviceProperty_VirtualMasterBalance
> >         };
> > 
> >         AudioObjectPropertyScope kAudioObjectPropertyElementMain = kAudioObjectPropertyElementMaster;
> > 
> >         #define kAudioAggregateDeviceMainSubDeviceKey "master"
> > 
> >     #endif
> > #endif
> > 
> > #endif
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tested on beta xcode and 12.5.1 and it seems like this approach works. Hacky stuff like this doesn't seem like you should have to do this, but I'm unsure of another solution.
> > The nice part is that can just delete the C stuff and the actual framework doesn't change anything.
> > https://github.com/ryanfrancesconi/SimplyCoreAudio/blob/develop-C/Sources/SimplyCoreAudioC/SimplyCoreAudio.h
> > https://github.com/ryanfrancesconi/SimplyCoreAudio/tree/develop-C
> > Let me know if that seems like a good solution from your perspective, or is too gross.
> 
> That seems fine to me. However, running `swift build` using command line tools for Xcode 13.0 (beta 5):
> 
> ```
> % swift --version
> swift-driver version: 1.26.9 Apple Swift version 5.5 (swiftlang-1300.0.29.102 clang-1300.0.28.1)
> Target: x86_64-apple-macosx11.0
> ```
> 
> I am still getting:
> 
> ```
> % swift build    
> /Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:20:38: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainVolume': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
>         guard validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterVolume,
>                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                      kAudioHardwareServiceDeviceProperty_VirtualMainVolume
> AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterVolume:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been explicitly marked unavailable here
> public var kAudioHardwareServiceDeviceProperty_VirtualMasterVolume: AudioObjectPropertySelector { get }
>            ^
> /Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:33:52: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainVolume': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
>         guard let address = validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterVolume,
>                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                    kAudioHardwareServiceDeviceProperty_VirtualMainVolume
> AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterVolume:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been explicitly marked unavailable here
> public var kAudioHardwareServiceDeviceProperty_VirtualMasterVolume: AudioObjectPropertySelector { get }
>            ^
> /Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:45:52: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainVolume': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
>         guard let address = validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterVolume,
>                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                    kAudioHardwareServiceDeviceProperty_VirtualMainVolume
> AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterVolume:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been explicitly marked unavailable here
> public var kAudioHardwareServiceDeviceProperty_VirtualMasterVolume: AudioObjectPropertySelector { get }
>            ^
> /Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:80:52: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterBalance' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainBalance': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
>         guard let address = validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterBalance,
>                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                    kAudioHardwareServiceDeviceProperty_VirtualMainBalance
> AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterBalance:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterBalance' has been explicitly marked unavailable here
> public var kAudioHardwareServiceDeviceProperty_VirtualMasterBalance: AudioObjectPropertySelector { get }
>            ^
> /Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:96:52: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterBalance' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainBalance': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
>         guard let address = validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterBalance,
>                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                    kAudioHardwareServiceDeviceProperty_VirtualMainBalance
> AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterBalance:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterBalance' has been explicitly marked unavailable here
> public var kAudioHardwareServiceDeviceProperty_VirtualMasterBalance: AudioObjectPropertySelector { get }
>            ^
> /Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:20:38: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainVolume': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
>         guard validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterVolume,
>                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                      kAudioHardwareServiceDeviceProperty_VirtualMainVolume
> AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterVolume:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been explicitly marked unavailable here
> public var kAudioHardwareServiceDeviceProperty_VirtualMasterVolume: AudioObjectPropertySelector { get }
>            ^
> /Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:33:52: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainVolume': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
>         guard let address = validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterVolume,
>                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                    kAudioHardwareServiceDeviceProperty_VirtualMainVolume
> AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterVolume:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been explicitly marked unavailable here
> public var kAudioHardwareServiceDeviceProperty_VirtualMasterVolume: AudioObjectPropertySelector { get }
>            ^
> /Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:45:52: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainVolume': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
>         guard let address = validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterVolume,
>                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                    kAudioHardwareServiceDeviceProperty_VirtualMainVolume
> AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterVolume:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been explicitly marked unavailable here
> public var kAudioHardwareServiceDeviceProperty_VirtualMasterVolume: AudioObjectPropertySelector { get }
>            ^
> /Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:80:52: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterBalance' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainBalance': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
>         guard let address = validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterBalance,
>                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                    kAudioHardwareServiceDeviceProperty_VirtualMainBalance
> AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterBalance:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterBalance' has been explicitly marked unavailable here
> public var kAudioHardwareServiceDeviceProperty_VirtualMasterBalance: AudioObjectPropertySelector { get }
>            ^
> /Users/ruben/src/experimental/SimplyCoreAudio/Sources/SimplyCoreAudio/Public/AudioDevice+VirtualMasterOutput.swift:96:52: error: 'kAudioHardwareServiceDeviceProperty_VirtualMasterBalance' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainBalance': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift
>         guard let address = validAddress(selector: kAudioHardwareServiceDeviceProperty_VirtualMasterBalance,
>                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                    kAudioHardwareServiceDeviceProperty_VirtualMainBalance
> AudioToolbox.kAudioHardwareServiceDeviceProperty_VirtualMasterBalance:2:12: note: 'kAudioHardwareServiceDeviceProperty_VirtualMasterBalance' has been explicitly marked unavailable here
> public var kAudioHardwareServiceDeviceProperty_VirtualMasterBalance: AudioObjectPropertySelector { get }
>            ^
> ```
> 
> Works fine using command line tools for Xcode 12.5.1, though.
> 
> Running macOS 11.5.2 here.

My bad! I was building against the wrong branch — everything works just fine!

```
ruben@Pro16 SimplyCoreAudio % swift --version
swift-driver version: 1.26.9 Apple Swift version 5.5 (swiftlang-1300.0.29.102 clang-1300.0.28.1)
Target: x86_64-apple-macosx11.0
ruben@Pro16 SimplyCoreAudio % swift build    
[32/32] Build complete!
ruben@Pro16 SimplyCoreAudio % git branch
  add-stable
* develop-C
```

**Comment by ryanfrancesconi** [comment]
oh good, i was starting to be confused how that could be!

so cool to merge?

**Comment by ryanfrancesconi** [comment]
I could also see some justification for having some C helpers in there (in terms of this child framework) somewhere at times, though you've done a splendid job keeping it all in swift so far

**Comment by ryanfrancesconi** [comment]
also, this didn't actually work in 12.5.1, though I didn't really get why. It still was trying to find kAudioObjectPropertyElementMain. That's what prompted doing it in C.

```swift
            if #available(macOS 12, *) {
                return kAudioObjectPropertyElementMain
            } else {
                return kAudioObjectPropertyElementMaster
            }
```

**Comment by rnine** [comment]
> I could also see some justification for having some C helpers in there (in terms of this child framework) somewhere at times, though you've done a splendid job keeping it all in swift so far

Thanks! A little C won't hurt for as long as it is integrated transparently into the swift package that framework users consume. 

> also, this didn't actually work in 12.5.1, though I didn't really get why. It still was trying to find kAudioObjectPropertyElementMain. That's what prompted doing it in C.
> 
> ```swift
>             if #available(macOS 12, *) {
>                 return kAudioObjectPropertyElementMain
>             } else {
>                 return kAudioObjectPropertyElementMaster
>             }
> ```

Yeah, the symbols are defined only when linking against the latest macOS SDKs that come with Xcode 13.0+. So, not a good solution.

> oh good, i was starting to be confused how that could be!
> 
> so cool to merge?

Yes, fine to merge indeed!

**Comment by ryanfrancesconi** [comment]
ok!
